import { View, Text, StyleSheet, ScrollView, Pressable } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { colors, fontSize, fontWeight, radius, spacing } from "@/src/theme";

export default function TermsScreen() {
  const router = useRouter();
  return (
    <View style={{ flex: 1, backgroundColor: colors.surface }} testID="terms-screen">
      <SafeAreaView edges={["top"]}>
        <View style={styles.header}>
          <Pressable onPress={() => router.back()} style={styles.iconBtn} testID="terms-back">
            <Ionicons name="chevron-back" size={22} color={colors.onSurface} />
          </Pressable>
          <Text style={styles.title}>Terms & Conditions</Text>
          <View style={styles.iconBtn} />
        </View>
      </SafeAreaView>
      <ScrollView contentContainerStyle={styles.body} showsVerticalScrollIndicator={false}>
        <Text style={styles.updated}>Last updated: June 2026</Text>

        <Section title="1. Acceptance">
          By downloading, installing, or using DailyHub AI (the “app”) developed by Shivam
          Innovation, you agree to be bound by these Terms & Conditions.
        </Section>

        <Section title="2. License">
          We grant you a personal, non-transferable, non-exclusive license to use the app on your
          personal devices for lawful purposes. You may not resell, sublicense, decompile, or
          reverse-engineer the app.
        </Section>

        <Section title="3. User content">
          You retain full ownership of the notes, todos, habits, expenses and chats you create. By
          using cloud sync, you grant us a limited license to store and process this content solely
          to provide the service to you.
        </Section>

        <Section title="4. Acceptable use">
          {`• Do not use the app for illegal, harmful, or abusive activity.\n• Do not attempt to overload our servers, bypass rate limits, or scrape our AI endpoints.\n• Do not use AI features to generate hateful, sexual, or violent content targeting real persons.`}
        </Section>

        <Section title="5. AI disclaimer">
          AI responses are generated by third-party models and may be inaccurate. Do not rely on
          them for medical, legal, or financial decisions. Use your own judgment.
        </Section>

        <Section title="6. Premium subscription">
          Premium features are optional. Prices are shown in-app before purchase. Google Play’s
          refund policy applies. Cancel any time from Play Store subscriptions.
        </Section>

        <Section title="7. Termination">
          We may suspend or terminate your access if you materially breach these Terms. You may stop
          using the app at any time by uninstalling it.
        </Section>

        <Section title="8. Warranty & liability">
          The app is provided “AS IS” without warranties of any kind. To the maximum extent
          permitted by law, Shivam Innovation shall not be liable for indirect or consequential
          damages arising from your use of the app.
        </Section>

        <Section title="9. Governing law">
          These Terms are governed by the laws of India. Disputes will be resolved in the courts of
          the state where Shivam Innovation is registered.
        </Section>

        <Section title="10. Contact">
          {`Shivam Innovation\nsupport@shivaminnovation.dev`}
        </Section>
      </ScrollView>
    </View>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      <Text style={styles.sectionBody}>{children}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  iconBtn: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: radius.md },
  title: { color: colors.onSurface, fontSize: fontSize.lg, fontWeight: fontWeight.bold },
  body: { paddingHorizontal: spacing.xl, paddingBottom: spacing.xxxl },
  updated: { color: colors.onSurfaceTertiary, fontSize: fontSize.sm, marginBottom: spacing.lg },
  section: { marginBottom: spacing.xl },
  sectionTitle: { color: colors.onSurface, fontSize: fontSize.base, fontWeight: fontWeight.bold, marginBottom: spacing.xs },
  sectionBody: { color: colors.onSurfaceSecondary, fontSize: fontSize.sm, lineHeight: 22 },
});
